---
title: "tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cov2)
library(stats)
library(rbenchmark)
```

To use function wrapper function of ‘cor_function'
Put the input vector of x and y, correlation of interested and whether conducting a statistical test

```{r}
x=rnorm(15)
y=rnorm(15)
```

Example of pearson, without test

```{r}
cor_function(x,y,method="pearson",stat_test=FALSE)
```

Example of pearson, with test

```{r}
cor_function(x,y,method="pearson",stat_test=TRUE)
```

Example of spearman, without test

```{r}
cor_function(x,y,method="spearman",stat_test=FALSE)
```

Example pf spearman, with test

```{r}
cor_function(x,y,method="spearman",stat_test=TRUE)
```

Continuous Integration

```{r}
usethis::use_github_action("check-release")
```

Check for the efficiency and accuracy

```{r}
usethis::use_testthat()
devtools::test()
```

```{r}
x=rnorm(1000000)
y=rnorm(1000000)
benchmark(cor.test(x,y,method="pearson"))
benchmark(cor_function(x,y,method="pearson",stat_test=TRUE))

```