test_that("cor_function works", {
  x1=rnorm(100)
  x2=rnorm(100)
  x3=rnorm(100)
  x4=rnorm(100)
  x5=rnorm(100)
  x6=rnorm(100)
  x7=rnorm(100)
  x8=rnorm(100)
  x9=rnorm(100)
  x10=rnorm(100)
  y1=rnorm(100)
  y2=rnorm(100)
  y3=rnorm(100)
  y4=rnorm(100)
  y5=rnorm(100)
  y6=rnorm(100)
  y7=rnorm(100)
  y8=rnorm(100)
  y9=rnorm(100)
  y10=rnorm(100)
  expect_equal(round(cor_function(x1,y1,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x1,y1,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x2,y2,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x2,y2,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x3,y3,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x3,y3,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x4,y4,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x4,y4,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x5,y5,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x5,y5,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x6,y6,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x6,y6,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x7,y7,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x7,y7,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x8,y8,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x8,y8,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x9,y9,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x9,y9,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x10,y10,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x10,y10,method="pearson")$estimate),4))
})
