test_that("cor_function works", {
  x1=rnorm(1000)
  x2=rnorm(2000)
  x3=rnorm(3000)
  x4=rnorm(4000)
  x5=rnorm(5000)
  x6=rnorm(6000)
  x7=rnorm(7000)
  x8=rnorm(8000)
  x9=rnorm(9000)
  x10=rnorm(10000)
  y1=rnorm(1000)
  y2=rnorm(2000)
  y3=rnorm(3000)
  y4=rnorm(4000)
  y5=rnorm(5000)
  y6=rnorm(6000)
  y7=rnorm(7000)
  y8=rnorm(8000)
  y9=rnorm(9000)
  y10=rnorm(10000)
  expect_equal(round(cor_function(x1,y1,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x1,y1,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x2,y2,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x2,y2,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x3,y3,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x3,y3,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x4,y4,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x4,y4,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x5,y5,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x5,y5,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x6,y6,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x6,y6,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x7,y7,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x7,y7,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x8,y8,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x8,y8,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x9,y9,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x9,y9,method="pearson")$estimate),4))
  expect_equal(round(cor_function(x10,y10,method="pearson",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x10,y10,method="pearson")$estimate),4))
  expect_equal(cor_function(x1,y1,method="pearson",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x1,y1,method="pearson")$p.value),2))
  expect_equal(cor_function(x2,y2,method="pearson",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x2,y2,method="pearson")$p.value),2))
  expect_equal(cor_function(x3,y3,method="pearson",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x3,y3,method="pearson")$p.value),2))
  expect_equal(cor_function(x4,y4,method="pearson",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x4,y4,method="pearson")$p.value),2))
  expect_equal(cor_function(x5,y5,method="pearson",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x5,y5,method="pearson")$p.value),2))
  expect_equal(cor_function(x6,y6,method="pearson",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x6,y6,method="pearson")$p.value),2))
  expect_equal(cor_function(x7,y7,method="pearson",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x7,y7,method="pearson")$p.value),2))
  expect_equal(cor_function(x8,y8,method="pearson",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x8,y8,method="pearson")$p.value),2))
  expect_equal(cor_function(x9,y9,method="pearson",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x9,y9,method="pearson")$p.value),2))
  expect_equal(cor_function(x10,y10,method="pearson",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x10,y10,method="pearson")$p.value),2))
  expect_equal(round(cor_function(x1,y1,method="pearson",stat_test = TRUE)$statistic,4), round(as.numeric(cor.test(x1,y1,method="pearson")$statistic),4))
  expect_equal(round(cor_function(x2,y2,method="pearson",stat_test = TRUE)$statistic,4), round(as.numeric(cor.test(x2,y2,method="pearson")$statistic),4))
  expect_equal(round(cor_function(x3,y3,method="pearson",stat_test = TRUE)$statistic,4), round(as.numeric(cor.test(x3,y3,method="pearson")$statistic),4))
  expect_equal(round(cor_function(x4,y4,method="pearson",stat_test = TRUE)$statistic,4), round(as.numeric(cor.test(x4,y4,method="pearson")$statistic),4))
  expect_equal(round(cor_function(x5,y5,method="pearson",stat_test = TRUE)$statistic,4), round(as.numeric(cor.test(x5,y5,method="pearson")$statistic),4))
  expect_equal(round(cor_function(x6,y6,method="pearson",stat_test = TRUE)$statistic,4), round(as.numeric(cor.test(x6,y6,method="pearson")$statistic),4))
  expect_equal(round(cor_function(x7,y7,method="pearson",stat_test = TRUE)$statistic,4), round(as.numeric(cor.test(x7,y7,method="pearson")$statistic),4))
  expect_equal(round(cor_function(x8,y8,method="pearson",stat_test = TRUE)$statistic,4), round(as.numeric(cor.test(x8,y8,method="pearson")$statistic),4))
  expect_equal(round(cor_function(x9,y9,method="pearson",stat_test = TRUE)$statistic,4), round(as.numeric(cor.test(x9,y9,method="pearson")$statistic),4))
  expect_equal(round(cor_function(x10,y10,method="pearson",stat_test = TRUE)$statistic,4), round(as.numeric(cor.test(x10,y10,method="pearson")$statistic),4))
  expect_equal(cor_function(x1,y1,method="pearson",stat_test = TRUE)$df, as.numeric(cor.test(x1,y1,method="pearson")$parameter))
  expect_equal(cor_function(x2,y2,method="pearson",stat_test = TRUE)$df, as.numeric(cor.test(x2,y2,method="pearson")$parameter))
  expect_equal(cor_function(x3,y3,method="pearson",stat_test = TRUE)$df, as.numeric(cor.test(x3,y3,method="pearson")$parameter))
  expect_equal(cor_function(x4,y4,method="pearson",stat_test = TRUE)$df, as.numeric(cor.test(x4,y4,method="pearson")$parameter))
  expect_equal(cor_function(x5,y5,method="pearson",stat_test = TRUE)$df, as.numeric(cor.test(x5,y5,method="pearson")$parameter))
  expect_equal(cor_function(x6,y6,method="pearson",stat_test = TRUE)$df, as.numeric(cor.test(x6,y6,method="pearson")$parameter))
  expect_equal(cor_function(x7,y7,method="pearson",stat_test = TRUE)$df, as.numeric(cor.test(x7,y7,method="pearson")$parameter))
  expect_equal(cor_function(x8,y8,method="pearson",stat_test = TRUE)$df, as.numeric(cor.test(x8,y8,method="pearson")$parameter))
  expect_equal(cor_function(x9,y9,method="pearson",stat_test = TRUE)$df, as.numeric(cor.test(x9,y9,method="pearson")$parameter))
  expect_equal(cor_function(x10,y10,method="pearson",stat_test = TRUE)$df, as.numeric(cor.test(x10,y10,method="pearson")$parameter))
  
  
  expect_equal(round(cor_function(x1,y1,method="spearman",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x1,y1,method="spearman")$estimate),4))
  expect_equal(round(cor_function(x2,y2,method="spearman",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x2,y2,method="spearman")$estimate),4))
  expect_equal(round(cor_function(x3,y3,method="spearman",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x3,y3,method="spearman")$estimate),4))
  expect_equal(round(cor_function(x4,y4,method="spearman",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x4,y4,method="spearman")$estimate),4))
  expect_equal(round(cor_function(x5,y5,method="spearman",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x5,y5,method="spearman")$estimate),4))
  expect_equal(round(cor_function(x6,y6,method="spearman",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x6,y6,method="spearman")$estimate),4))
  expect_equal(round(cor_function(x7,y7,method="spearman",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x7,y7,method="spearman")$estimate),4))
  expect_equal(round(cor_function(x8,y8,method="spearman",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x8,y8,method="spearman")$estimate),4))
  expect_equal(round(cor_function(x9,y9,method="spearman",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x9,y9,method="spearman")$estimate),4))
  expect_equal(round(cor_function(x10,y10,method="spearman",stat_test = TRUE)$correlation,4), round(as.numeric(cor.test(x10,y10,method="spearman")$estimate),4))
  expect_equal(cor_function(x1,y1,method="spearman",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x1,y1,method="spearman")$p.value),2))
  expect_equal(cor_function(x2,y2,method="spearman",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x2,y2,method="spearman")$p.value),2))
  expect_equal(cor_function(x3,y3,method="spearman",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x3,y3,method="spearman")$p.value),2))
  expect_equal(cor_function(x4,y4,method="spearman",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x4,y4,method="spearman")$p.value),2))
  expect_equal(cor_function(x5,y5,method="spearman",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x5,y5,method="spearman")$p.value),2))
  expect_equal(cor_function(x6,y6,method="spearman",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x6,y6,method="spearman")$p.value),2))
  expect_equal(cor_function(x7,y7,method="spearman",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x7,y7,method="spearman")$p.value),2))
  expect_equal(cor_function(x8,y8,method="spearman",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x8,y8,method="spearman")$p.value),2))
  expect_equal(cor_function(x9,y9,method="spearman",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x9,y9,method="spearman")$p.value),2))
  expect_equal(cor_function(x10,y10,method="spearman",stat_test = TRUE)$p.value, round(as.numeric(cor.test(x10,y10,method="spearman")$p.value),2))
  expect_equal(round(cor_function(x1,y1,method="spearman",stat_test = TRUE)$s,4), round(as.numeric(cor.test(x1,y1,method="spearman")$statistic),4))
  expect_equal(round(cor_function(x2,y2,method="spearman",stat_test = TRUE)$s,4), round(as.numeric(cor.test(x2,y2,method="spearman")$statistic),4))
  expect_equal(round(cor_function(x3,y3,method="spearman",stat_test = TRUE)$s,4), round(as.numeric(cor.test(x3,y3,method="spearman")$statistic),4))
  expect_equal(round(cor_function(x4,y4,method="spearman",stat_test = TRUE)$s,4), round(as.numeric(cor.test(x4,y4,method="spearman")$statistic),4))
  expect_equal(round(cor_function(x5,y5,method="spearman",stat_test = TRUE)$s,4), round(as.numeric(cor.test(x5,y5,method="spearman")$statistic),4))
  expect_equal(round(cor_function(x6,y6,method="spearman",stat_test = TRUE)$s,4), round(as.numeric(cor.test(x6,y6,method="spearman")$statistic),4))
  expect_equal(round(cor_function(x7,y7,method="spearman",stat_test = TRUE)$s,4), round(as.numeric(cor.test(x7,y7,method="spearman")$statistic),4))
  expect_equal(round(cor_function(x8,y8,method="spearman",stat_test = TRUE)$s,4), round(as.numeric(cor.test(x8,y8,method="spearman")$statistic),4))
  expect_equal(round(cor_function(x9,y9,method="spearman",stat_test = TRUE)$s,4), round(as.numeric(cor.test(x9,y9,method="spearman")$statistic),4))
  expect_equal(round(cor_function(x10,y10,method="spearman",stat_test = TRUE)$s,4), round(as.numeric(cor.test(x10,y10,method="spearman")$statistic),4))

})
