# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kandall <- function(x, y) {
    .Call('_cov2_kandall', PACKAGE = 'cov2', x, y)
}

